import type { Metadata } from "next";
import { Geist, Geist_Mono, DynaPuff } from "next/font/google";
import "./globals.css";
import { IdentityProvider } from '@/context/IdentityContext'

const dynaPuff = DynaPuff({
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}
        className={`${dynaPuff.style.fontFamily} ${geistMono.variable} antialiased`}
      >
      <IdentityProvider>
        {children}
        </IdentityProvider>
      </body>
    </html>
  );
}
